### ISSUE TITLE
Multithreaded execution caveats

### ISSUE THREAD

**Issue by etki** [jonahsnider/benchmark#282]
Hey. Basically i'm just a java passerby looking for a side fun.

First of all, this is outstanding project in the js world. So far i've seen only two frameworks that know that the warmup phase is necessary. 

However, what caught my eye is the multithreaded execution. The idea of speeding things up is tempting, but it puts the benchmarks in the shared resource position, meaning they would affect each other. And what i'm speaking of is not even a file/database or the runtime, that would be avoidable - the real bottleneck is the hardware. Most often we speak about CPU-bound benchmarks (who cares about anything else and why would they use this kind of tool then?), and even the server CPUs have frequency-changing quirks to squeeze the performance to the max when there is a headroom: https://www.intel.com/content/www/us/en/support/articles/000056901/processors/intel-xeon-processors.html. Not only the numbers themselves would be different, which would be a simple scale problem, there would always be the longest suite running, which will be boosted after everyone else has finished. One more thing to be mentioned is that there are more implicit shared resources like L3 cache - if two benchmarks are actively using large amounts of memory, then their combination would not perform the same as standalone executions even if core frequency would be fixed. I also think that the runtime itself should be treated as a black box - i have no idea what is the current state of v8 resource sharing, but i would expect that there are still. some shared resources and possibility of cross-influence, even if each thread is powered by a separate JIT instance.

The obvious question here is - am i talking complete rubbish, and if i'm not, is the problem really at scale? I think it is:

```
# suites/generator.js
import {Suite} from '@jonahsnider/benchmark';

export default source => {
    const filename = source.split('/').pop()

    return new Suite(`baseline#${filename}`, {
        filepath: source,
        run: {
            trials: 1_000_000,
        },
        warmup: {
            durationMs: 1_000,
        },
    })
    .addTest(`baseline#${filename}`, () => Math.random());
}
```

```
# suites/suite-a.js
import generator from './generator.js';

export default generator(import.meta.url);
```

```
# index.js
import {Benchmark} from '@jonahsnider/benchmark';

import a from './suites/suite-a.js';
import b from './suites/suite-b.js';
import c from './suites/suite-c.js';
import d from './suites/suite-d.js';
import e from './suites/suite-e.js';
import f from './suites/suite-f.js';
import g from './suites/suite-g.js';
import h from './suites/suite-h.js';
import i from './suites/suite-i.js';
import j from './suites/suite-j.js';

const suites = [a, b, c, d, e, f, g, h, i, j];

function report(results) {
    let count = 0;
    let cumulative = 0;
    for (let [_, tests] of results.entries()) {
        for (let [_, histogram] of tests.entries()) {
            console.log(histogram.mean)
            count++;
            cumulative += histogram.mean;
        }
    }

    if (count === 0) {
        console.error('How come no results were passed?');
    } else {
        console.log(`Averaged mean: ${cumulative / count}`);
    }
}

// Yes, i have a weird (and in fact, underclocked!) setup with 10 physical cores
for (let concurrency of [1, 2, 4, 8, 10]) {
    const benchmark = new Benchmark();
    for (let k = 0; k < Math.min((concurrency), suites.length); k++) {
        await benchmark.addSuite(suites[k], {threaded: true});
    }
    const results = await benchmark.runSuites();
    console.log(`Completed run for concurrency = ${concurrency}`)
    report(results);
}
```

Results:

```
Completed run for concurrency = 1
54.715967
Averaged mean: 54.715967
Completed run for concurrency = 2
54.429196
55.035571
Averaged mean: 54.7323835
Completed run for concurrency = 4
55.109227
55.721342
56.284646
57.450292
Averaged mean: 56.14137675
Completed run for concurrency = 8
59.323925
60.471768
60.734908
61.096808
60.473214
60.162151
60.704296
61.432521
Averaged mean: 60.549948875
Completed run for concurrency = 10
62.168136
62.201302
63.597637
63.212276
64.161704
62.050188
62.120548
64.684839
80.155428
80.130049
Averaged mean: 66.44821069999999
```

TBH, this is a garbage run, because i have a ton of other processes running (including this very chromium), and that's likely why the last two tests are obvious outliers. However, you can see a strong trend here. As i'm only calling for a pseudorandom, the tests should be completely independent one of other, but they are definitely connected.

In my opinion (does anybody even care about that?) the perfect microbenching framework should create a runner process per test to isolate all possible cross-influence and run the tests sequentially. I do not think that something should be completely ripped off here - but i guess at least README deserves a mention that the results obtaining in a multithreaded run are not to be compared with the sequential execution.

**Comment by jonahsnider** [comment]
Hey! Thanks for the kind words & interest in this project. As you pointed out, it's really difficult to get truly accurate measurements when there's so much external noise that influences benchmarks. I just released an update that allows you to run multithreaded benchmarks sequentially, rather than in parallel, which should help make results a little more accurate.

Unfortunately, even with changes like that the benchmark results can still be very consistent from things totally unrelated to the code. One project you may be interested in is [CodSpeed](https://codspeed.io/), which tries to measure the CPU time of JS code, rather than the overall execution time. Not perfect, but a big step in the right direction.

Hope this helps, and my apologies for the very late response.
